# Generated by Django 2.1.1 on 2018-11-22 09:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20181121_1601'),
        ('billings', '0001_initial'),
        ('refunds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='billings.BillingProfile')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.OrderItem')),
            ],
            options={
                'db_table': 'refunds_refund_request',
            },
        ),
        migrations.AddField(
            model_name='refundpolicy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refundpolicy',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='refundpolicy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
