# Generated by Django 2.1.1 on 2018-11-22 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_category_slug'),
        ('refunds', '0002_auto_20181122_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refundpolicy',
            name='item',
        ),
        migrations.AddField(
            model_name='refundpolicy',
            name='category',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='refunds', to='categories.Category'),
            preserve_default=False,
        ),
    ]
