# Generated by Django 2.1.1 on 2018-11-22 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_auto_20181107_1851'),
        ('refunds', '0003_auto_20181122_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundpolicy',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='refunds', to='companies.Company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='refundpolicy',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='refunds', to='categories.Category'),
        ),
    ]
