# Generated by Django 2.1.1 on 2018-11-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('provider', 'provider'), ('customer', 'customer')], default='admin', max_length=100),
        ),
    ]
