# Generated by Django 2.1.1 on 2018-11-01 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_sidebar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='admin',
            new_name='is_admin',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='staff',
            new_name='is_staff',
        ),
    ]
