# Generated by Django 2.1.1 on 2018-11-22 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
        ('ratings', '0003_auto_20181122_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='fiscal_year',
            field=models.ForeignKey(default=2075.076, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ratings', to='settings.FiscalYear'),
            preserve_default=False,
        ),
    ]
