# Generated by Django 2.1.1 on 2018-11-07 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20181107_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockrecord',
            old_name='discounted_percentage',
            new_name='discount_percentage',
        ),
    ]
