# Generated by Django 2.1.1 on 2018-11-11 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_item_in_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='in_cart',
        ),
    ]
