# Generated by Django 2.1.1 on 2018-11-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20181120_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='document',
            field=models.ImageField(upload_to=''),
        ),
    ]
