# Generated by Django 2.1.1 on 2018-11-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_auto_20181121_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='specification',
            field=models.TextField(default='specs'),
            preserve_default=False,
        ),
    ]
