# Generated by Django 2.1.1 on 2018-11-01 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'max_length': "Length Shouldn't exceed 64 characters "}, max_length=64)),
                ('address', models.CharField(error_messages={'max_length': "Length Shouldn't exceed 64 characters"}, max_length=64)),
                ('postal', models.CharField(error_messages={'max_length': "Length Shouldn't exceed 20 characters"}, max_length=20)),
                ('city', models.CharField(error_messages={'max_length': "Length Shouldn't exceed 64 characters"}, max_length=64)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Invalid Email Address')])),
                ('phone_number', models.CharField(error_messages={'max_length': "Length Shouldn't exceed 15 digits "}, max_length=15)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'companies_company',
            },
        ),
    ]
