# Generated by Django 2.1.1 on 2018-11-01 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_companyadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyadmin',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_admins', to='companies.Company'),
        ),
    ]
