# Generated by Django 2.1.1 on 2018-11-07 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_companyadmin_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyadmin',
            name='password',
            field=models.CharField(default='umesh123', max_length=20),
            preserve_default=False,
        ),
    ]
