# Generated by Django 2.1.1 on 2018-11-07 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_companyadmin_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyadmin',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_admins', to='companies.Company'),
        ),
        migrations.AlterField(
            model_name='companyadmin',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
