# Generated by Django 2.1.1 on 2018-11-07 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_auto_20181107_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyadmin',
            name='full_name',
            field=models.CharField(default='Umesh Chaudahry', error_messages={'max_length': 'Length Shouldnot exceed 120 Characters'}, max_length=120),
            preserve_default=False,
        ),
    ]
