# Generated by Django 2.1.1 on 2018-11-07 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_companycategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='companycategory',
            options={'verbose_name': 'Company Category', 'verbose_name_plural': 'Company Categories'},
        ),
        migrations.AddField(
            model_name='companycategory',
            name='company',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_category', to='companies.Company'),
            preserve_default=False,
        ),
    ]
