# Generated by Django 2.1.1 on 2018-11-21 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
        ('orders', '0003_auto_20181120_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fiscal_year',
            field=models.ForeignKey(default=2075.076, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='settings.FiscalYear'),
            preserve_default=False,
        ),
    ]
