# Generated by Django 2.1.1 on 2018-11-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_fiscal_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('created ', 'created'), ('paid', 'paid'), ('delivered', 'delivered'), ('processed', 'processed'), ('refunded', 'refunded')], default='created', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created ', 'created'), ('paid', 'paid'), ('delivered', 'delivered'), ('processed', 'processed'), ('refunded', 'refunded')], default='created', max_length=255),
        ),
    ]
